services:
  backend:
    image: ghcr.io/ngocnhan2k4/ai-recruit-be:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    command: >
      sh -c "npx drizzle-kit push && npm run build && npm run start:prod"

  elasticsearch:
    build: "./pkg/elasticsearch"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge

volumes:
  esdata:
