services:
  backend:
    image: ghcr.io/ngocnhan2k4/ai-recruit-be:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8001:8001"
    command: >
      sh -c "npm run build && npm run start:prod"
    labels:
      - "env=prod"
      - "project=airecruit"
