export const TAG_MAP: Record<string, string> = {
  "job": "career",
  "jobs": "career",
  "jobhunting": "job hunting",
  "job-hunting": "job hunting",
  "resumes": "resume",
  "cvs": "cv",
  "recruiting": "recruitment",
  "recruit": "recruitment",
  "intern": "internship",
  "interns": "internship",
  "freelancing": "freelance",
  "remote": "remote work",
  "remotework": "remote work",
  "salaries": "salary",
  "promotions": "promotion",
  "softskills": "soft skills",
  "soft-skills": "soft skills",
  "time-management": "time management",
  "timemanagement": "time management",
  "stress-management": "stress management",
  "stressmanagement": "stress management",
  "mental-health": "mental health",
  "mentalhealth": "mental health",
  "careerswitch": "career switch",
  "career-switch": "career switch",
  "careerpath": "career path",
  "career-path": "career path",
  "worklifebalance": "work life balance",
  "work-life-balance": "work life balance",
  "remoteteam": "remote team",
  "remote-team": "remote team",
  "bestpractices": "best practices",
  "best-practices": "best practices",
  "codereview": "code review",
  "code-review": "code review",
  "cleancode": "clean code",
  "clean-code": "clean code",
  "opensource": "open source",
  "open-source": "open source",
  "systemdesign": "system design",
  "system-design": "system design",
  "softwarearchitecture": "software architecture",
  "software-architecture": "software architecture",
  "uxui": "ux/ui",
  "ux-ui": "ux/ui"
};

export const IGNORED_TAGS = new Set([
  "beginners", "beginner", "tutorial", "help", "discussion", "web", "programming", 
  "coding", "news", "productivity", "tips", "showdev", "watercooler", "challenge",
  "learning", "development", "developer", "software", "tech", "technology", 
  "blog", "article", "personal", "general", "misc", "other", "test", "demo",
  "begin", "back", "dnd", "journal"
]);

export const SEED_TAGS: string[] = [
  "career", "interview", "resume", "cv", "job hunting", "recruitment", "internship", "freelance",
  "remote work", "salary", "promotion", "soft skills", "productivity", "leadership", "management",
  "communication", "mentorship", "teamwork", "work life balance", "burnout", "motivation", "mindset",
  "agile", "scrum", "best practices", "code review", "clean code", "refactoring", "testing",
  "open source", "documentation", "system design", "software architecture", "security", "performance",
  "scalability", "ux/ui", "accessibility", "startup", "entrepreneurship", "business", "marketing",
  "networking", "negotiation", "personal brand", "blogging", "learning", "education", "career path",
  "remote team", "collaboration", "creativity", "problem solving", "decision making", "time management",
  "stress management", "mental health", "career switch", "freelancer", "consulting", "outsourcing"
];
