[request_definition]
r = sub, obj, act
r2 = sub, org_id, obj, act

[policy_definition]
p = sub, obj, act, eft
p2 = sub, dom_type, obj, act, eft

[role_definition]
g = _, _
g2 = _, _, _

[policy_effect]
# allow if some allow and no deny
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))
e2 = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
# system-level roles (no org context)
m = keyMatch2(r.obj, p.obj) && regexMatch(r.act, p.act) && g(r.sub, p.sub)    # organization-level roles
m2 = (((g2(r2.sub, p2.sub, r2.org_id) || g2(r2.sub, p2.sub, "*")) && p2.dom_type == "org")) && keyMatch2(r2.obj, p2.obj) && regexMatch(r2.act, p2.act)
