export enum Action {
  ActionInsert = 1,
  ActionUpdate = 2,
  ActionDelete = 3,
  ActionActive = 4,
  ActionInactive = 5,
  ActionCancel = 6,
  ActionApprove = 7,
  ActionApply = 8,
  ActionSave = 9,
  ActionInvite = 10,
  ActionKick = 11,
  ActionLeave = 12,
  ActionVerify = 13,
  ActionConfirm = 14,
  ActionRestore = 15,
  ActionLink = 16,
  ActionUnlink = 17,
  ActionComplete = 18,
  ActionSend = 19,
}

export const ActionNameMap: Record<Action, string> = {
  [Action.ActionInsert]: "Insert",
  [Action.ActionUpdate]: "Update",
  [Action.ActionDelete]: "Delete",
  [Action.ActionActive]: "Active",
  [Action.ActionInactive]: "Inactive",
  [Action.ActionCancel]: "Cancel",
  [Action.ActionApprove]: "Approve",
  [Action.ActionApply]: "Apply",
  [Action.ActionSave]: "Save",
  [Action.ActionInvite]: "Invite",
  [Action.ActionKick]: "Kick",
  [Action.ActionLeave]: "Leave",
  [Action.ActionVerify]: "Verify",
  [Action.ActionConfirm]: "Confirm",
  [Action.ActionRestore]: "Restore",
  [Action.ActionLink]: "Link",
  [Action.ActionUnlink]: "Unlink",
  [Action.ActionComplete]: "Complete",
  [Action.ActionSend]: "Send",
};
