export enum OrganizationRole {
  // Organization-level roles
  ORGANIZATION_OWNER = "ORGANIZATION_OWNER",
  ORGANIZATION_ADMIN = "ORGANIZATION_ADMIN",
  ORGANIZATION_EDITOR = "ORGANIZATION_EDITOR",
  ORGANIZATION_VIEWER = "ORGANIZATION_VIEWER",

  // Organization content roles
  ORGANIZATION_CONTENT_ADMIN = "ORGANIZATION_CONTENT_ADMIN",
  ORGANIZATION_CONTENT_EDITOR = "ORGANIZATION_CONTENT_EDITOR",
  ORGANIZATION_CONTENT_VIEWER = "ORGANIZATION_CONTENT_VIEWER",

  // Organization recruiter roles
  ORGANIZATION_RECRUITER_ADMIN = "ORGANIZATION_RECRUITER_ADMIN",
  ORGANIZATION_RECRUITER_EDITOR = "ORGANIZATION_RECRUITER_EDITOR",
  ORGANIZATION_RECRUITER_VIEWER = "ORGANIZATION_RECRUITER_VIEWER",

  // Organization analyst roles
  ORGANIZATION_ANALYST_ADMIN = "ORGANIZATION_ANALYST_ADMIN",
  ORGANIZATION_ANALYST_EDITOR = "ORGANIZATION_ANALYST_EDITOR",
  ORGANIZATION_ANALYST_VIEWER = "ORGANIZATION_ANALYST_VIEWER",

  // Organization employee role
  ORGANIZATION_EMPLOYEE = "ORGANIZATION_EMPLOYEE",

  ANONYMOUSLY = "ANONYMOUSLY",
}
