name: Crawl Jobs

on:
  schedule:
    # Runs at 17:30
    - cron: "30 10 * * *"
  workflow_dispatch: # allows manual trigger too

jobs:
  run-crawler:
    strategy:
      matrix:
        env: [dev, prod]

    environment: ${{ matrix.env }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        working-directory: ./crawl_jobs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        id: run_crawler
        working-directory: ./crawl_jobs
        run: python main.py --db-url "${{ secrets.DATABASE_URL }}" --gha-output "$GITHUB_OUTPUT" --pages 30 --linkedin-keywords "AI Engineer"

      - name: Notify Slack
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.CRAWL_CHANNEL }}
          SLACK_CHANNEL: crawl
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
          SLACK_TITLE: "📊 Kết quả crawl việc làm (${{ matrix.env }})"
          SLACK_MESSAGE: |
            🕒 Thời gian: ${{ steps.run_crawler.outputs.crawl_time }}

            🔹 ITviec: ${{ steps.run_crawler.outputs.itviec }} jobs
            🔹 TopCV: ${{ steps.run_crawler.outputs.topcv }} jobs
            🔹 JobsGo: ${{ steps.run_crawler.outputs.jobsgo }} jobs
            🔹 Linkedin: ${{ steps.run_crawler.outputs.linkedin }} jobs

            ✅ Status: ${{ job.status }}
